<xsl:when test="name()='a'"><xsl:call-template name="node"><xsl:with-param name="tag">a</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='abbr'"><xsl:call-template name="node"><xsl:with-param name="tag">a</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='acronym'"><xsl:call-template name="node"><xsl:with-param name="tag">a</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='address'"><xsl:call-template name="node"><xsl:with-param name="tag">a</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='applet'"><xsl:call-template name="node"><xsl:with-param name="tag">a</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='area'"><xsl:call-template name="node"><xsl:with-param name="tag">a</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='b'"><xsl:call-template name="node"><xsl:with-param name="tag">b</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='base'"><xsl:call-template name="node"><xsl:with-param name="tag">b</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='basefont'"><xsl:call-template name="node"><xsl:with-param name="tag">b</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='bdo'"><xsl:call-template name="node"><xsl:with-param name="tag">b</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='big'"><xsl:call-template name="node"><xsl:with-param name="tag">b</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='blockquote'"><xsl:call-template name="node"><xsl:with-param name="tag">b</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='body'"><xsl:call-template name="node"><xsl:with-param name="tag">b</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='br'"><xsl:call-template name="node"><xsl:with-param name="tag">b</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='button'"><xsl:call-template name="node"><xsl:with-param name="tag">b</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='caption'"><xsl:call-template name="node"><xsl:with-param name="tag">c</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='center'"><xsl:call-template name="node"><xsl:with-param name="tag">c</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='cite'"><xsl:call-template name="node"><xsl:with-param name="tag">c</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='code'"><xsl:call-template name="node"><xsl:with-param name="tag">c</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='col'"><xsl:call-template name="node"><xsl:with-param name="tag">c</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='colgroup'"><xsl:call-template name="node"><xsl:with-param name="tag">c</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='dd'"><xsl:call-template name="node"><xsl:with-param name="tag">d</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='del'"><xsl:call-template name="node"><xsl:with-param name="tag">d</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='dfn'"><xsl:call-template name="node"><xsl:with-param name="tag">d</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='dir'"><xsl:call-template name="node"><xsl:with-param name="tag">d</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='div'"><xsl:call-template name="node"><xsl:with-param name="tag">d</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='dl'"><xsl:call-template name="node"><xsl:with-param name="tag">d</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='dt'"><xsl:call-template name="node"><xsl:with-param name="tag">d</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='em'"><xsl:call-template name="node"><xsl:with-param name="tag">e</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='fieldset'"><xsl:call-template name="node"><xsl:with-param name="tag">f</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='font'"><xsl:call-template name="node"><xsl:with-param name="tag">f</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='form'"><xsl:call-template name="node"><xsl:with-param name="tag">f</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='h1'"><xsl:call-template name="node"><xsl:with-param name="tag">h</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='h2'"><xsl:call-template name="node"><xsl:with-param name="tag">h</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='h3'"><xsl:call-template name="node"><xsl:with-param name="tag">h</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='h4'"><xsl:call-template name="node"><xsl:with-param name="tag">h</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='h5'"><xsl:call-template name="node"><xsl:with-param name="tag">h</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='h6'"><xsl:call-template name="node"><xsl:with-param name="tag">h</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='head'"><xsl:call-template name="node"><xsl:with-param name="tag">h</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='hr'"><xsl:call-template name="node"><xsl:with-param name="tag">h</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='html'"><xsl:call-template name="node"><xsl:with-param name="tag">h</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='i'"><xsl:call-template name="node"><xsl:with-param name="tag">i</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='iframe'"><xsl:call-template name="node"><xsl:with-param name="tag">i</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='img'"><xsl:call-template name="node"><xsl:with-param name="tag">i</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='input'"><xsl:call-template name="node"><xsl:with-param name="tag">i</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='ins'"><xsl:call-template name="node"><xsl:with-param name="tag">i</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='isindex'"><xsl:call-template name="node"><xsl:with-param name="tag">i</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='kbd'"><xsl:call-template name="node"><xsl:with-param name="tag">k</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='label'"><xsl:call-template name="node"><xsl:with-param name="tag">l</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='legend'"><xsl:call-template name="node"><xsl:with-param name="tag">l</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='li'"><xsl:call-template name="node"><xsl:with-param name="tag">l</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='link'"><xsl:call-template name="node"><xsl:with-param name="tag">l</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='map'"><xsl:call-template name="node"><xsl:with-param name="tag">m</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='menu'"><xsl:call-template name="node"><xsl:with-param name="tag">m</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='meta'"><xsl:call-template name="node"><xsl:with-param name="tag">m</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='noframes'"><xsl:call-template name="node"><xsl:with-param name="tag">n</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='noscript'"><xsl:call-template name="node"><xsl:with-param name="tag">n</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='object'"><xsl:call-template name="node"><xsl:with-param name="tag">o</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='ol'"><xsl:call-template name="node"><xsl:with-param name="tag">o</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='optgroup'"><xsl:call-template name="node"><xsl:with-param name="tag">o</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='option'"><xsl:call-template name="node"><xsl:with-param name="tag">o</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='p'"><xsl:call-template name="node"><xsl:with-param name="tag">p</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='param'"><xsl:call-template name="node"><xsl:with-param name="tag">p</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='pre'"><xsl:call-template name="node"><xsl:with-param name="tag">p</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='q'"><xsl:call-template name="node"><xsl:with-param name="tag">q</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='s'"><xsl:call-template name="node"><xsl:with-param name="tag">s</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='samp'"><xsl:call-template name="node"><xsl:with-param name="tag">s</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='script'"><xsl:call-template name="node"><xsl:with-param name="tag">s</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='select'"><xsl:call-template name="node"><xsl:with-param name="tag">s</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='small'"><xsl:call-template name="node"><xsl:with-param name="tag">s</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='span'"><xsl:call-template name="node"><xsl:with-param name="tag">s</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='strike'"><xsl:call-template name="node"><xsl:with-param name="tag">s</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='strong'"><xsl:call-template name="node"><xsl:with-param name="tag">s</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='style'"><xsl:call-template name="node"><xsl:with-param name="tag">s</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='sub'"><xsl:call-template name="node"><xsl:with-param name="tag">s</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='sup'"><xsl:call-template name="node"><xsl:with-param name="tag">s</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='table'"><xsl:call-template name="node"><xsl:with-param name="tag">t</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='tbody'"><xsl:call-template name="node"><xsl:with-param name="tag">t</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='td'"><xsl:call-template name="node"><xsl:with-param name="tag">t</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='textarea'"><xsl:call-template name="node"><xsl:with-param name="tag">t</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='tfoot'"><xsl:call-template name="node"><xsl:with-param name="tag">t</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='thead'"><xsl:call-template name="node"><xsl:with-param name="tag">t</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='title'"><xsl:call-template name="node"><xsl:with-param name="tag">t</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='tr'"><xsl:call-template name="node"><xsl:with-param name="tag">t</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='tt'"><xsl:call-template name="node"><xsl:with-param name="tag">t</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='u'"><xsl:call-template name="node"><xsl:with-param name="tag">u</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='ul'"><xsl:call-template name="node"><xsl:with-param name="tag">u</xsl:with-param></xsl:call-template></xsl:when>
<xsl:when test="name()='var'"><xsl:call-template name="node"><xsl:with-param name="tag">v</xsl:with-param></xsl:call-template></xsl:when>